const API_ENDPOINT = '/api/ldap/search';
const INTERNAL_SERVER_ERROR_CODE = 500;
const INVALID_CREDENTIALS_ERROR_CODE = 49;
const INVALID_CREDENTIALS_ERROR_MESSAGE = 'Invalid credentials';
const ACTIVE_DIRECTORY_USERNAME = 'userPrincipalName';

module.exports = {
    API_ENDPOINT,
    INTERNAL_SERVER_ERROR_CODE,
    INVALID_CREDENTIALS_ERROR_CODE,
    INVALID_CREDENTIALS_ERROR_MESSAGE,
    ACTIVE_DIRECTORY_USERNAME
};